#!/bin/bash

if [ ! -d ~/Software/apache-flume-1.3.1-bin ]; then
  cd ~/Software
  wget http://apache.mirrors.pair.com/flume/1.3.1/apache-flume-1.3.1-bin.tar.gz

  tar xzf apache-flume-1.3.1-bin.tar.gz

  cd apache-flume-1.3.1-bin
fi

sudo mkdir -p /var/log/apache/flumeSpool
sudo chown erewhon /var/log/apache/flumeSpool

